server:
  port: 8081
spring:
  application:
    name: myApp
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  redis:

    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
file:
  uploadPath: F:\\MyProjects\\Test\\source
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    mapped-statements-ordered: true # 开启查询返回Map结果有序
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
#  config-location: classpath:configs/mybatis.conf.xml # mybatis配置文件所在路径
  type-aliases-package: com.twave.myapplication.Entity # 所有Entity别名类所在包
logging:
  level:
    root: info
    com.twave.myapplication: debug
