server:
  port: 8081
spring:
  application:
    name: myApp
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  redis:
    host:
    port:
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
file:
  uploadPath: /home/Files
##服务器上使用 /home/Files 路径
#file.address.service=/home/Files
##本地使用 E://Projects/springBoot/upload 路径
#file.address.service=E://Projects/springBoot/upload